const API=window.ENGINE_API_URL||"";
const $=id=>document.getElementById(id);
let defaults=null,plan=null,lastResult=null,currentScenario="BASE",frontierChart=null,inventoryChart=null,capexChart=null;
async function api(path,opt={}){const r=await fetch(API+path,opt);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||"HTTP "+r.status);return b}
function msg(id,t,c){$(id).textContent=t||"";$(id).className="message "+(c||"")}
function fmt(x,d=1){return x==null||Number.isNaN(Number(x))?"—":Number(x).toLocaleString("ru-RU",{maximumFractionDigits:d})}
function clone(x){return JSON.parse(JSON.stringify(x))}
function view(v){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+v))}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>view(b.dataset.view));
function sync(){$("planJson").value=JSON.stringify(plan,null,2)}
function renderOrders(){let y=defaults.years,h="<table><thead><tr><th>Источник</th>"+y.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>";defaults.sources.forEach(s=>{h+="<tr><td><strong>"+s.name+"</strong><br><small>"+s.id+" · cap "+fmt(s.capacity)+" t/y</small></td>";y.forEach(yr=>{let v=plan.orders?.[s.id]?.[yr]??0;h+='<td><input type="number" min="0" step="0.1" data-s="'+s.id+'" data-y="'+yr+'" value="'+v+'"></td>'});h+="</tr>"});$("ordersEditor").innerHTML=h+"</tbody></table>";$("ordersEditor").querySelectorAll("input").forEach(i=>i.oninput=e=>{let s=e.target.dataset.s,y=Number(e.target.dataset.y);plan.orders[s]??={};plan.orders[s][y]=Number(e.target.value)||0})}
function renderReserve(){let y=defaults.years,h="<table><thead><tr><th>Источник</th>"+y.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>";defaults.sources.forEach(s=>{h+="<tr><td>"+s.name+"</td>";y.forEach(yr=>{let v=plan.reserved?.[s.id]?.[yr]??0;h+='<td><input type="number" min="0" step="0.1" data-s="'+s.id+'" data-y="'+yr+'" value="'+v+'"></td>'});h+="</tr>"});$("reserveEditor").innerHTML=h+"</tbody></table>";$("reserveEditor").querySelectorAll("input").forEach(i=>i.oninput=e=>{let s=e.target.dataset.s,y=Number(e.target.dataset.y);plan.reserved[s]??={};plan.reserved[s][y]=Number(e.target.value)||0})}
function investmentDefault(id){let o=defaults.investments.find(x=>x.id===id),first=defaults.years[0],service=o.earliest_in_service_year||(id==="EARTH_NEW"?first+2:first),n=(o.stage_labels||[]).length||1;return{stage_dates:Array(n).fill(first+"-01"),in_service:service+"-01"}}
function renderInvestments(){let sel=new Set(Object.keys(plan.investments||{}));$("investmentEditor").innerHTML=defaults.investments.map(o=>'<label class="investment"><input type="checkbox" data-i="'+o.id+'" '+(sel.has(o.id)?"checked":"")+'><div><strong>'+o.id+'</strong><small>'+o.kind+" → "+o.target_id+" · CAPEX "+fmt(o.capex,0)+" млн</small></div></label>").join("");$("investmentEditor").querySelectorAll("input").forEach(i=>i.onchange=e=>{let id=e.target.dataset.i;if(e.target.checked)plan.investments[id]=investmentDefault(id);else delete plan.investments[id];sync()})}
function renderStock(){let h="";defaults.sources.forEach(s=>{let v=(plan.initial_stock||[]).filter(x=>x.source===s.id).reduce((a,x)=>a+Number(x.tons||0),0);h+='<div class="stock"><label>'+s.name+'</label><input type="number" min="0" step="0.1" data-stock="'+s.id+'" value="'+v+'"></div>'});$("stockEditor").innerHTML=h;$("stockEditor").querySelectorAll("input").forEach(i=>i.oninput=e=>{let id=e.target.dataset.stock,v=Number(e.target.value)||0;plan.initial_stock=(plan.initial_stock||[]).filter(x=>x.source!==id);if(v>0)plan.initial_stock.push({source:id,tons:v});sync()})}
function editors(){$("yearRange").textContent=defaults.years[0]+"—"+defaults.years[defaults.years.length-1];renderOrders();renderReserve();renderInvestments();renderStock();sync()}
function loadPlan(p){plan=clone(p);editors()}
async function optimize(){msg("planMessage","Оптимизатор выполняется…");$("optimizeBtn").disabled=true;try{sync();let ids=["BASE"];if($("stressScenario").checked)ids.push("MANDATORY_STRESS");lastResult=await api("/api/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan:plan,scenario_ids:ids,run_frontier:true})});plan=clone(lastResult.plan);editors();$("resultJson").textContent=JSON.stringify(lastResult,null,2);renderDashboard();renderFrontier();msg("planMessage",lastResult.feasible?"План найден без HARD-нарушений":"Найден лучший доступный план; проверьте dashboard",lastResult.feasible?"good":"");view("dashboard")}catch(e){msg("planMessage",e.message,"bad")}finally{$("optimizeBtn").disabled=false}}
function renderDashboard(){let r=lastResult?.scenarios?.[currentScenario];if(!r){$("dashboardContent").innerHTML='<div class="dashboard-empty"><h3>Нет результата для сценария</h3></div>';return}let k=r.kpis||{},good=r.feasible;$("dashboardContent").innerHTML='<div class="result-status '+(good?"good":"bad")+'"><div><strong>'+(good?"Допустимый план":"Есть HARD-нарушения")+'</strong><p>'+(r.meta?.name||currentScenario)+'</p></div><span class="status '+(good?"ok":"bad")+'">'+(good?"FEASIBLE":"CHECK")+'</span></div><div class="kpis"><div class="kpi"><div class="label">PV COST</div><div class="value">'+fmt(k.pv_cost)+' млн</div></div><div class="kpi"><div class="label">CAPEX</div><div class="value">'+fmt(k.capex_total)+' млн</div></div><div class="kpi"><div class="label">SHORTAGE</div><div class="value">'+fmt(k.shortage_total)+' т</div></div><div class="kpi"><div class="label">MIN SL TOTAL</div><div class="value">'+fmt((k.min_sl_total||0)*100,2)+'%</div></div><div class="kpi"><div class="label">MIN SL CRITICAL</div><div class="value">'+fmt((k.min_sl_critical||0)*100,2)+'%</div></div></div><div class="charts"><div class="card"><div class="card-head"><div><h3>Запас топлива</h3><span>Запас и требуемый резерв.</span></div></div><div class="chart-box"><canvas id="inventoryChart"></canvas></div></div><div class="card"><div class="card-head"><div><h3>CAPEX</h3><span>Капитальные затраты по годам.</span></div></div><div class="chart-box"><canvas id="capexChart"></canvas></div></div></div><div class="two-col"><div class="card"><div class="card-head"><h3>Годовая физика</h3></div><div id="yearlyTable" class="table-scroll"></div></div><div class="card"><div class="card-head"><h3>Нарушения / проверки</h3></div><div id="violations"></div></div></div>';drawCharts(r);renderYearly(r);renderViolations(r)}
function drawCharts(r){let y=r.yearly||[],labels=y.map(x=>x.year);if(inventoryChart)inventoryChart.destroy();if(capexChart)capexChart.destroy();inventoryChart=new Chart($("inventoryChart"),{type:"line",data:{labels:labels,datasets:[{label:"Запас, т",data:y.map(x=>x.inventory_close),tension:.25},{label:"Резерв, т",data:y.map(x=>x.reserve_required),tension:.25}]},options:{responsive:true,maintainAspectRatio:false}});let c=r.costs||[];capexChart=new Chart($("capexChart"),{type:"bar",data:{labels:c.map(x=>x.year),datasets:[{label:"CAPEX, млн у.е.",data:c.map(x=>x.capex)}]},options:{responsive:true,maintainAspectRatio:false}})}
function renderYearly(r){let cols=["year","demand_total","served_total","shortage_total","inventory_close","reserve_required","reserve_covered"];$("yearlyTable").innerHTML="<table><thead><tr>"+cols.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+(r.yearly||[]).map(row=>"<tr>"+cols.map(x=>"<td>"+fmt(row[x])+"</td>").join("")+"</tr>").join("")+"</tbody></table>"}
function renderViolations(r){let vs=r.violations||[];$("violations").innerHTML=vs.length?vs.map(v=>'<div class="violation"><strong>'+(v.severity||"CHECK")+" · "+(v.code||"")+'</strong><span>'+(v.message||v.detail||"")+(v.year?" · "+v.year:"")+"</span></div>").join(""):'<div class="message good">Нарушений не обнаружено.</div>'}
document.querySelectorAll(".scenario-btn").forEach(b=>b.onclick=()=>{currentScenario=b.dataset.scenario;document.querySelectorAll(".scenario-btn").forEach(x=>x.classList.toggle("active",x===b));renderDashboard()});
function renderFrontier(){let pts=lastResult?.frontier||[],valid=pts.filter(p=>p.status==="evaluated"&&p.capex_total!=null&&p.service_level_base!=null);if(frontierChart)frontierChart.destroy();frontierChart=new Chart($("frontierChart"),{type:"scatter",data:{datasets:[{label:"Investment candidates",data:valid.map(p=>({x:p.capex_total,y:p.service_level_base*100})),pointRadius:6}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{title:{display:true,text:"CAPEX, млн у.е."}},y:{title:{display:true,text:"MIN SL BASE, %"}}}}});$("frontierTable").innerHTML=pts.length?"<table><thead><tr><th>Инвестиции</th><th>CAPEX</th><th>SL BASE</th><th>SL STRESS</th><th>Shortage</th><th>Status</th></tr></thead><tbody>"+pts.map(p=>"<tr><td>"+(p.selected?"★ ":"")+(p.investments||[]).join(", ")+"</td><td>"+fmt(p.capex_total,0)+"</td><td>"+fmt((p.service_level_base||0)*100,2)+"%</td><td>"+fmt((p.service_level_stress||0)*100,2)+"%</td><td>"+fmt((p.shortage_base||0)+(p.shortage_stress||0))+"</td><td>"+p.status+"</td></tr>").join("")+"</tbody></table>":"<div class=\"message\">Запустите оптимизацию, чтобы получить frontier.</div>"}
$("loadTemplate").onclick=()=>loadPlan(defaults.plan_template);$("optimizeBtn").onclick=optimize;
$("formatJson").onclick=()=>{try{$("planJson").value=JSON.stringify(JSON.parse($("planJson").value),null,2);msg("planMessage","JSON корректен","good")}catch(e){msg("planMessage","Ошибка JSON: "+e.message,"bad")}};
$("applyJson").onclick=()=>{try{loadPlan(JSON.parse($("planJson").value));msg("planMessage","JSON применён","good");view("plan")}catch(e){msg("planMessage","Ошибка JSON: "+e.message,"bad")}};
async function boot(){try{defaults=await api("/api/defaults");let h=await api("/api/health");$("connection").textContent="API: online";$("connection").className="status ok";$("engineInfo").textContent="engine "+h.engine_version;loadPlan(defaults.plan_template)}catch(e){$("connection").textContent="API: offline";$("connection").className="status bad";msg("planMessage","Не удалось подключиться к backend: "+e.message,"bad")}}boot();