const API=window.ENGINE_API_URL||"";
const $=id=>document.getElementById(id);
let defaults=null,plan=null,lastResult=null,currentScenario="BASE";
async function api(path,opt={}){const r=await fetch(API+path,opt);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||"HTTP "+r.status);return b}
function msg(id,t,c){$(id).textContent=t||"";$(id).className="message "+(c||"")}
function fmt(x,d=1){return x==null||Number.isNaN(Number(x))?"—":Number(x).toLocaleString("ru-RU",{maximumFractionDigits:d})}
function clone(x){return JSON.parse(JSON.stringify(x))}
function view(v){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+v))}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>view(b.dataset.view));
function sync(){$("planJson").value=JSON.stringify(plan,null,2)}
function renderOrders(){let y=defaults.years,h="<table><thead><tr><th>Источник</th>"+y.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>";defaults.sources.forEach(s=>{h+="<tr><td><strong>"+s.name+"</strong><br><small>"+s.id+" · cap "+fmt(s.capacity)+" t/y</small></td>";y.forEach(yr=>{let v=plan.orders?.[s.id]?.[yr]??0;h+='<td><input type="number" min="0" step="0.1" data-s="'+s.id+'" data-y="'+yr+'" value="'+v+'"></td>'});h+="</tr>"});$("ordersEditor").innerHTML=h+"</tbody></table>";$("ordersEditor").querySelectorAll("input").forEach(i=>i.oninput=e=>{let s=e.target.dataset.s,y=Number(e.target.dataset.y);plan.orders[s]??={};plan.orders[s][y]=Number(e.target.value)||0})}
function renderReserve(){let y=defaults.years,h="<table><thead><tr><th>Источник</th>"+y.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>";defaults.sources.forEach(s=>{let disabled=s.requires_reservation?"":" disabled title=\"Для этого канала резерв всегда равен полной мощности\"";h+="<tr><td>"+s.name+"</td>";y.forEach(yr=>{let v=s.requires_reservation?(plan.reserved?.[s.id]?.[yr]??0):s.capacity;h+='<td><input type="number" min="0" step="0.1" data-s="'+s.id+'" data-y="'+yr+'" value="'+v+'"'+disabled+'></td>'});h+="</tr>"});$("reserveEditor").innerHTML=h+"</tbody></table>";$("reserveEditor").querySelectorAll("input:not([disabled])").forEach(i=>i.oninput=e=>{let s=e.target.dataset.s,y=Number(e.target.dataset.y);plan.reserved[s]??={};plan.reserved[s][y]=Number(e.target.value)||0})}
function investmentDefault(id){let o=defaults.investments.find(x=>x.id===id);if(!o?.default_schedule)throw new Error("Нет стандартного investment schedule для "+id);return clone(o.default_schedule)}
function renderInvestments(){let sel=new Set(Object.keys(plan.investments||{}));$("investmentEditor").innerHTML=defaults.investments.map(o=>'<label class="investment"><input type="checkbox" data-i="'+o.id+'" '+(sel.has(o.id)?"checked":"")+'><div><strong>'+o.id+'</strong><small>'+o.kind+" → "+o.target_id+" · CAPEX "+fmt(o.capex,0)+" млн</small></div></label>").join("");$("investmentEditor").querySelectorAll("input").forEach(i=>i.onchange=e=>{let id=e.target.dataset.i;if(e.target.checked)plan.investments[id]=investmentDefault(id);else delete plan.investments[id];sync()})}
function renderStock(){let h="";defaults.sources.forEach(s=>{let v=(plan.initial_stock||[]).filter(x=>x.source===s.id).reduce((a,x)=>a+Number(x.tons||0),0);h+='<div class="stock"><label>'+s.name+'</label><input type="number" min="0" step="0.1" data-stock="'+s.id+'" value="'+v+'"></div>'});$("stockEditor").innerHTML=h;$("stockEditor").querySelectorAll("input").forEach(i=>i.oninput=e=>{let id=e.target.dataset.stock,v=Number(e.target.value)||0;plan.initial_stock=(plan.initial_stock||[]).filter(x=>x.source!==id);if(v>0)plan.initial_stock.push({source:id,tons:v});sync()})}
function editors(){$("yearRange").textContent=defaults.years[0]+"—"+defaults.years[defaults.years.length-1];renderOrders();renderReserve();renderInvestments();renderStock();sync()}
function loadPlan(p){plan=clone(p);editors()}
async function optimize(){msg("planMessage","Оптимизатор выполняется…");$("optimizeBtn").disabled=true;try{sync();let ids=["BASE"];if($("stressScenario").checked)ids.push("MANDATORY_STRESS");lastResult=await api("/api/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan:plan,scenario_ids:ids,run_frontier:true})});currentScenario="BASE";document.querySelectorAll(".scenario-btn").forEach(x=>x.classList.toggle("active",x.dataset.scenario==="BASE"));const stressButton=document.querySelector('.scenario-btn[data-scenario="MANDATORY_STRESS"]');if(stressButton)stressButton.disabled=!lastResult.scenarios?.MANDATORY_STRESS;plan=clone(lastResult.plan);editors();$("resultJson").textContent=JSON.stringify(lastResult,null,2);renderDashboard();renderFrontier();msg("planMessage",lastResult.feasible?"План найден без HARD-нарушений":"Найден лучший доступный план; проверьте dashboard",lastResult.feasible?"good":"");view("dashboard")}catch(e){msg("planMessage",e.message,"bad")}finally{$("optimizeBtn").disabled=false}}
function renderDashboard(){let r=lastResult?.scenarios?.[currentScenario];if(!r){$("dashboardContent").innerHTML='<div class="dashboard-empty"><h3>Нет результата для сценария</h3></div>';return}let k=r.kpis||{},good=r.feasible;$("dashboardContent").innerHTML='<div class="result-status '+(good?"good":"bad")+'"><div><strong>'+(good?"Допустимый план":"Есть HARD-нарушения")+'</strong><p>'+(r.meta?.name||currentScenario)+'</p></div><span class="status '+(good?"ok":"bad")+'">'+(good?"FEASIBLE":"CHECK")+'</span></div><div class="kpis"><div class="kpi"><div class="label">PV COST</div><div class="value">'+fmt(k.pv_cost)+' млн</div></div><div class="kpi"><div class="label">CAPEX</div><div class="value">'+fmt(k.capex_total)+' млн</div></div><div class="kpi"><div class="label">SHORTAGE</div><div class="value">'+fmt(k.shortage_total)+' т</div></div><div class="kpi"><div class="label">MIN SL TOTAL</div><div class="value">'+fmt((k.min_sl_total||0)*100,2)+'%</div></div><div class="kpi"><div class="label">MIN SL CRITICAL</div><div class="value">'+fmt((k.min_sl_critical||0)*100,2)+'%</div></div></div><div class="charts"><div class="card"><div class="card-head"><div><h3>Запас топлива</h3><span>Запас и требуемый резерв.</span></div></div><div class="chart-box"><div id="inventoryChart" class="svg-chart"></div></div></div><div class="card"><div class="card-head"><div><h3>CAPEX</h3><span>Капитальные затраты по годам.</span></div></div><div class="chart-box"><div id="capexChart" class="svg-chart"></div></div></div></div><div class="two-col"><div class="card"><div class="card-head"><h3>Годовая физика</h3></div><div id="yearlyTable" class="table-scroll"></div></div><div class="card"><div class="card-head"><h3>Нарушения / проверки</h3></div><div id="violations"></div></div></div>';drawCharts(r);renderYearly(r);renderViolations(r)}
function chartSvg(el,series,kind){
 const w=760,h=300,p={l:58,r:18,t:22,b:42},iw=w-p.l-p.r,ih=h-p.t-p.b;
 const vals=series.flatMap(s=>s.data.map(Number).filter(Number.isFinite));
 const max=Math.max(...vals,1),min=Math.min(...vals,0);
 const sx=i=>p.l+(series[0].data.length===1?iw/2:iw*i/(series[0].data.length-1));
 const sy=v=>p.t+ih-(v-min)/(max-min||1)*ih;
 const esc=s=>String(s).replaceAll("&","&amp;").replaceAll("<","&lt;");
 let svg='<svg viewBox="0 0 '+w+' '+h+'">';
 [0,.5,1].forEach(t=>{const y=p.t+ih*t,v=max-(max-min)*t;svg+='<line x1="'+p.l+'" y1="'+y+'" x2="'+(w-p.r)+'" y2="'+y+'" class="grid"/><text x="'+(p.l-8)+'" y="'+(y+4)+'" text-anchor="end" class="axis">'+esc(fmt(v))+'</text>'});
 const n=series[0].data.length;
 if(n){[0,Math.floor((n-1)/2),n-1].filter((v,i,a)=>a.indexOf(v)===i).forEach(i=>svg+='<text x="'+sx(i)+'" y="'+(h-14)+'" text-anchor="middle" class="axis">'+esc(series[0].labels[i])+'</text>')}
 series.forEach((s,si)=>{if(kind==="bar"){const bw=Math.max(4,iw/Math.max(n,1)*.55);s.data.forEach((v,i)=>{const y=sy(Number(v));svg+='<rect x="'+(sx(i)-bw/2)+'" y="'+y+'" width="'+bw+'" height="'+(p.t+ih-y)+'" class="bar b'+si+'"/>'})}else{const pts=s.data.map((v,i)=>sx(i)+","+sy(Number(v))).join(" ");svg+='<polyline points="'+pts+'" class="line l'+si+'" fill="none"/>';s.data.forEach((v,i)=>svg+='<circle cx="'+sx(i)+'" cy="'+sy(Number(v))+'" r="3" class="dot d'+si+'"/>')}});
 svg+='<line x1="'+p.l+'" y1="'+(p.t+ih)+'" x2="'+(w-p.r)+'" y2="'+(p.t+ih)+'" class="axis-line"/></svg>';
 $(el).innerHTML=svg;
}
function drawCharts(r){
 const y=r.yearly||[];
 chartSvg("inventoryChart",[
  {labels:y.map(x=>x.year),data:y.map(x=>x.inventory_close)},
  {labels:y.map(x=>x.year),data:y.map(x=>x.reserve_required)}
 ],"line");
 const c=r.costs||[];
 chartSvg("capexChart",[{labels:c.map(x=>x.year),data:c.map(x=>x.capex)}],"bar");
}
function renderYearly(r){let cols=["year","demand_total","served_total","shortage_total","inventory_close","reserve_required","reserve_covered"];$("yearlyTable").innerHTML="<table><thead><tr>"+cols.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+(r.yearly||[]).map(row=>"<tr>"+cols.map(x=>"<td>"+fmt(row[x])+"</td>").join("")+"</tr>").join("")+"</tbody></table>"}
function renderViolations(r){let vs=r.violations||[];$("violations").innerHTML=vs.length?vs.map(v=>'<div class="violation"><strong>'+(v.severity||"CHECK")+" · "+(v.code||"")+'</strong><span>'+(v.message||v.detail||"")+(v.year?" · "+v.year:"")+"</span></div>").join(""):'<div class="message good">Нарушений не обнаружено.</div>'}
document.querySelectorAll(".scenario-btn").forEach(b=>b.onclick=()=>{if(b.disabled)return;currentScenario=b.dataset.scenario;document.querySelectorAll(".scenario-btn").forEach(x=>x.classList.toggle("active",x===b));renderDashboard()});
function renderFrontier(){
 const pts=lastResult?.frontier||[],valid=pts.filter(p=>p.status==="evaluated"&&p.capex_total!=null&&p.service_level_base!=null);
 const el=$("frontierChart"),w=760,h=320,p={l:62,r:22,t:22,b:48};
 const xs=valid.map(q=>Number(q.capex_total)),ys=valid.map(q=>Number(q.service_level_base)*100);
 const xmax=Math.max(...xs,1),xmin=Math.min(...xs,0),ymin=Math.min(...ys,0),ymax=Math.max(...ys,100);
 const sx=v=>p.l+(v-xmin)/(xmax-xmin||1)*(w-p.l-p.r),sy=v=>p.t+(ymax-v)/(ymax-ymin||1)*(h-p.t-p.b);
 let svg='<svg viewBox="0 0 '+w+' '+h+'"><line x1="'+p.l+'" y1="'+(h-p.b)+'" x2="'+(w-p.r)+'" y2="'+(h-p.b)+'" class="axis-line"/><line x1="'+p.l+'" y1="'+p.t+'" x2="'+p.l+'" y2="'+(h-p.b)+'" class="axis-line"/><text x="'+(w/2)+'" y="'+(h-8)+'" text-anchor="middle" class="axis">CAPEX, млн у.е.</text><text transform="translate(15 '+(h/2)+') rotate(-90)" text-anchor="middle" class="axis">MIN SL BASE, %</text>';
 valid.forEach(q=>{svg+='<circle cx="'+sx(Number(q.capex_total))+'" cy="'+sy(Number(q.service_level_base)*100)+'" r="'+(q.selected?8:6)+'" class="frontier-point'+(q.selected?" selected":"")+'"><title>'+String(q.investments||[]).replaceAll("&","&amp;")+'</title></circle>'});
 svg+='</svg>';el.innerHTML=svg;
 $("frontierTable").innerHTML=pts.length?"<table><thead><tr><th>Инвестиции</th><th>CAPEX</th><th>SL BASE</th><th>SL STRESS</th><th>Shortage</th><th>Status</th></tr></thead><tbody>"+pts.map(p=>"<tr><td>"+(p.selected?"★ ":"")+(p.investments||[]).join(", ")+"</td><td>"+fmt(p.capex_total,0)+"</td><td>"+fmt((p.service_level_base||0)*100,2)+"%</td><td>"+fmt(p.service_level_stress==null?null:p.service_level_stress*100,2)+"%</td><td>"+fmt((p.shortage_base||0)+(p.shortage_stress||0))+"</td><td>"+p.status+"</td></tr>").join("")+"</tbody></table>":"<div class=\"message\">Запустите оптимизацию, чтобы получить frontier.</div>";
}
$("loadTemplate").onclick=()=>loadPlan(defaults.plan_template);$("optimizeBtn").onclick=optimize;
$("formatJson").onclick=()=>{try{$("planJson").value=JSON.stringify(JSON.parse($("planJson").value),null,2);msg("planMessage","JSON корректен","good")}catch(e){msg("planMessage","Ошибка JSON: "+e.message,"bad")}};
$("applyJson").onclick=()=>{try{loadPlan(JSON.parse($("planJson").value));msg("planMessage","JSON применён","good");view("plan")}catch(e){msg("planMessage","Ошибка JSON: "+e.message,"bad")}};
async function boot(){try{defaults=await api("/api/defaults");let h=await api("/api/health");$("connection").textContent="API: online";$("connection").className="status ok";$("engineInfo").textContent="engine "+h.engine_version;loadPlan(defaults.plan_template)}catch(e){$("connection").textContent="API: offline";$("connection").className="status bad";msg("planMessage","Не удалось подключиться к backend: "+e.message,"bad")}}boot();